# Generated by Django 5.0.4 on 2024-05-07 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(50)])),
                ('descripcion', models.TextField(validators=[django.core.validators.MinLengthValidator(1)])),
                ('category', models.CharField(choices=[('SuperHéroe', 'SuperHéroe'), ('Villano', 'Villano')], default='SuperHéroe', max_length=50)),
                ('ability', models.CharField(choices=[('Fuerza', 'Fuerza'), ('Velocidad', 'Velocidad'), ('Inteligencia', 'Inteligencia'), ('Telepatía', 'Telepatía'), ('Invisibilidad', 'Invisibilidad'), ('Vuelo', 'Vuelo'), ('Teletransportación', 'Teletransportación'), ('Manipulación del tiempo', 'Manipulación del tiempo'), ('Regeneración', 'Regeneración'), ('Manipulación de la energía', 'Manipulación de la energía')], default='Fuerza', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
