# Generated by Django 5.0.4 on 2024-05-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0003_alter_personaje_ability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Fuerza', 'Fuerza'), ('Velocidad', 'Velocidad'), ('Inteligencia', 'Inteligencia'), ('Telepatía', 'Telepatía'), ('Invisibilidad', 'Invisibilidad'), ('Vuelo', 'Vuelo'), ('Teletransportación', 'Teletransportación'), ('Manipulación del tiempo', 'Manipulación del tiempo'), ('Regeneración', 'Regeneración'), ('Manipulación de la energía', 'Manipulación de la energía')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='personaje',
            name='ability',
        ),
        migrations.AddField(
            model_name='personaje',
            name='abilities',
            field=models.ManyToManyField(to='mantenimientos.habilidad'),
        ),
    ]
