# Generated by Django 5.0.4 on 2024-05-08 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0005_remove_personaje_abilities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaje',
            name='name',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(50)]),
        ),
    ]
